version: "3.9"

networks:
  demo:
    driver: bridge
    name: demo

services:
  redis:
    container_name: redis
    image: redis
    networks:
      - demo
  retwis:
    build: retwis/.
    container_name: retwis
    image: retwis
    networks:
      - demo
    ports:
      - "9001:5000"     
